# ===== MySQL =====
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=utf8
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===== JPA =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# ===== Redis =====
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

server.port=8080

jwt.secret=${JWT_SECRET}
google.maps.browser-api-key=${GOOGLE_MAP_API:${GOOGLE_BROWSER_API_KEY:${GOOGLE_MAPS_API_KEY:}}}
google.maps.server-api-key=${GOOGLE_PRIVATE_API:${GOOGLE_SERVER_API_KEY:${GOOGLE_CLOUD_API_KEY:}}}
